### ISSUE TITLE
關於連現階段錯誤訊息

### ISSUE THREAD

**Issue by JonesChanTW** [MicrosoftDocs/cpp-docs.zh-tw#11]
不知道有沒有提供類似下列詳細的錯誤訊息說明頁面
1.最低安裝的Linux機器可能沒有gdb-server,於是造成普通SSH連線登入成功,但VC連線時總是失敗(因為還要有gdb-server)
2.標頭檔缺少原因分析與解決方案(扣除網路上某些文章說的,自己到相對路徑手動拷貝一份回本地端,這種手動方法常常會帶有後遺症,例如最後缺少某程式庫...之類)

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [在 Visual Studio 中設定 C++ Linux 專案](https://docs.microsoft.com/zh-tw/cpp/linux/configure-a-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/MicrosoftDocs/cpp-docs.zh-tw/blob/live/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @JonesChanTW
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
@JonesChanTW ，您好

非常感謝您的參與。但此意見反應與產品有關，煩請您使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來傳達建議。

如有與文件相關的意見反應，歡迎您透過此管道傳達給我們。

真心感謝您參與我們的文章。

Microsoft DOCS 國際小組
