### ISSUE TITLE
Get error message when open a existing folder with CMakeLists.txt file. The folder is under developing in WSL environment.

### ISSUE THREAD

**Issue by bbap-7fat** [MicrosoftDocs/cpp-docs.zh-tw#15]
When I FILE-&gt;OPEN-&gt;FOLDRER a folder, which has CMakeLists.txt, which is under developing in WSL and can make successfully, it shows error message as: There was an error activating the remote language server, CMake Language Services. For more details , please run devenv/log and examine the ..../ActivityLog.xml file

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [Visual Studio 中的 CMake 專案](https://docs.microsoft.com/zh-tw/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/cpp-docs.zh-tw/blob/live/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @bbap-7fat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by bbap-7fat** [comment]
Thanks, for more information I have:
- File->New->Project
- choose CMakeProject->next
VS can automatically start CMAKE process and it seems okay!

**Comment by V-vafune** [comment]
Hello, @bbap-7fat , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
