### ISSUE TITLE
gcd中文是最大公因數

### ISSUE THREAD

**Issue by tenyi** [MicrosoftDocs/cpp-docs.zh-tw#18]
gcd中文是最大公因數，不叫最大公除數

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: b715ca60-7363-e775-4dc5-7723dea2178a
* Version Independent ID: 276f458f-7934-e858-9475-3766496e6f4d
* Content: [&lt;numeric&gt; 函式](https://docs.microsoft.com/zh-tw/cpp/standard-library/numeric-functions?view=vs-2019)
* Content Source: [docs/standard-library/numeric-functions.md](https://github.com/MicrosoftDocs/cpp-docs.zh-tw/blob/live/docs/standard-library/numeric-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @tenyi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
@tenyi  您好： 

我們由衷感謝您的寶貴意見，並將竭盡全力改進您在 docs.microsoft.com 的體驗。在此之前，我們還需要更多的資訊，才能落實您的意見反應。可否請您提供更多的詳細資料，進一步說明您的意見？ 

順頌時祺 

Microsoft DOCS International Team

**Comment by tenyi** [comment]
https://zh.wikipedia.org/wiki/%E6%9C%80%E5%A4%A7%E5%85%AC%E5%9B%A0%E6%95%B8

從我的iPhone傳送

**Comment by CeciAc** [comment]
你好，@tenyi

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队
