### ISSUE TITLE
Updated correctness of link of vcpkg

### ISSUE THREAD

**Issue by stu85010** [MicrosoftDocs/cpp-docs.zh-tw#3]
Hi there,

I found your `docs/vcpkg.md` file has an issue, there's a fullwidth period char "。" nearby the link `https://github.com/Microsoft/vcpkg` to the vcpkg repository, that make user not able to go to this page by a single click:

🆗
```markdown
[https://github.com/Microsoft/vcpkg](https://github.com/Microsoft/vcpkg)。
```
result:
[https://github.com/Microsoft/vcpkg](https://github.com/Microsoft/vcpkg)。

🆖 
```markdown
https://github.com/Microsoft/vcpkg。
```
result:
https://github.com/Microsoft/vcpkg。

I'd updated the syntax in my fork, FYR:

https://github.com/stu85010/cpp-docs.zh-tw/commit/f71a7587c77ded904b17d4c794377e62c164cd4f

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #784](https://github.com/MicrosoftDocs/cpp-docs/issues/784) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
This issue was moved to the English to be fixed accordingly. 
Regards.
