### ISSUE TITLE
Hi,  about CWin32Heap 

### ISSUE THREAD

**Issue by RealCool1983** [MicrosoftDocs/cpp-docs.zh-tw#4]
I want to use CString for Multi thread safe, Should I do that ：

 //Use 0 instead of HEAP_NO_SERIALIZE 
  CWin32Heap stringHeap(0, 0, 0);  

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: b40f003e-3e06-b8a9-76b6-7b5a5ccd0d20
* Version Independent ID: ea49ba6d-1a5a-1cca-a977-7b27b6ea91e4
* Content: [避免堆積競爭](https://docs.microsoft.com/zh-tw/cpp/atl-mfc-shared/avoidance-of-heap-contention?view=vs-2019#feedback)
* Content Source: [docs/atl-mfc-shared/avoidance-of-heap-contention.md](https://github.com/MicrosoftDocs/cpp-docs.zh-tw/blob/live/docs/atl-mfc-shared/avoidance-of-heap-contention.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @RealCool1983

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
