### ISSUE TITLE
文件翻譯

### ISSUE THREAD

**Issue by FelixYangPersonal** [MicrosoftDocs/cpp-docs.zh-tw#7]
機器翻譯的品質太差了吧~
最近在調用WIN32跟GDI+，參閱相關文件，但是翻譯的描述品質實在是不行

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9c028ad6-bdd5-49ad-0c36-91af7f77e923
* Version Independent ID: e7886349-1db0-e040-697a-ba5f2b23c064
* Content: [特殊 CWinApp 服務](https://docs.microsoft.com/zh-tw/cpp/mfc/special-cwinapp-services?view=vs-2019#feedback)
* Content Source: [docs/mfc/special-cwinapp-services.md](https://github.com/MicrosoftDocs/cpp-docs.zh-tw/blob/live/docs/mfc/special-cwinapp-services.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @FelixYangPersonal
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
您好，@FelixYangPersonal
謝謝您的寶貴意見。問題中提及的頁面使用了機器翻譯，因此內容可能未必能夠完全理解。我們最近在右側新增了 [Read in English] (在英文版中閱讀) 選項，可讓您切換至英文版本而不需要變更語言設定。 
順頌時祺 
Microsoft DOCS 國際小組
